---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          set-safe-directory: ${{ github.workspace }}
      - uses: cliffano/command-docker-action@v1.4.0
        with:
          command: 'make deps ci'
          # Pinned to 2.9.0 for now due to "readline was closed" error with node 24.x
          image: cliffano/studio:2.9.0
          shell: bash
